# -*- coding: utf-8 -*-
"""字典清空輸出版(怪怪的).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nMnRv7vH3h2TfegHR_bWerOEF8UefI5Q
"""

a=["あ","か","さ","た","な","は","ま","や","ら","わ","が","ざ","だ","ば","ぱ"]
i=["い","き","し","ち","に","ひ","み","","り","","ぎ","じ","ぢ","び","ぴ"]
u=["う","く","す","つ","ぬ","ふ","む","ゆ","る","","ぐ","ず","づ","ぶ","ぷ"]
e=["え","け","せ","て","ね","へ","め","","れ","","げ","ぜ","で","べ","ぺ"]
o=["お","こ","そ","と","の","ほ","も","よ","ろ","を","ご","ぞ","ど","ぼ","ぽ"]

from IPython.display import clear_output
import time

file=open("voca1.txt","w",encoding="utf-8")
file.write("動詞變化單字表\n")

file2=open("voca2.txt","w",encoding="utf-8")
file2.write("動詞變化單字表\n")

#dictionary=open("dictionary.txt","a",encoding="utf-8")

list_1=[] #五段動詞
list_2=[] #上一段動詞
list_3=[] #下一段動詞
list_4=[] #ka行變格動詞
list_5=[] #sa行變革動詞

list_voca=[]

print("輸入日文辭書形，查詢動詞變化。")
print("欲結束查詢，可輸入leave\n")

returna=1

while returna!=0:
  verb=input("請輸入欲查詢動詞的辭書形:")
  time.sleep(0.2)
  clear_output()
  print("輸入日文辭書形，查詢動詞變化。")
  print("欲結束查詢，可輸入leave\n")

  

  while len(verb)<2:
    print("\n\n"+verb+"非日文動詞辭書型，請重新輸入\n\n\n")
    verb=input("請輸入欲查詢動詞的辭書形:")
    clear_output()
    print("輸入日文辭書形，查詢動詞變化。")
    print("欲結束查詢，可輸入leave\n")

  last_char = verb[-1]
  first_char = verb[0]
  last12_char = verb[-2]+verb[-1] #for sa ka

  ##判斷字尾是不是u段音(辭書行結尾一定是u段) 
  while (last_char not in u or last12_char=="ます") and verb.lower() !="leave":
    print("\n\n"+verb+"非日文動詞辭書型，請重新輸入\n\n\n")
    verb=input("請輸入欲查詢動詞的辭書形:")
    clear_output()
    print("輸入日文辭書形，查詢動詞變化。")
    print("欲結束查詢，可輸入leave\n")
    while len(verb)<2:
      print("\n\n"+verb+"非日文動詞辭書型，請重新輸入\n\n\n")
      verb=input("請輸入欲查詢動詞的辭書形:")
      clear_output()
      print("輸入日文辭書形，查詢動詞變化。")
      print("欲結束查詢，可輸入leave\n")

    last_char = verb[-1]
    first_char = verb[0]
    last12_char = verb[-2]+verb[-1] #for sa ka

  #str_lower_leave=verb.lower()
  #輸入leave時可以跳出迴圈結束程式
  if verb.lower()=="leave":    #or verb=="Leave"or verb=="LEAVE":
    returna=0
    break

  last_char = verb[-1]
  last2_char = verb[-2]
  last12_char = verb[-2]+verb[-1] #for sa ka
  front_chars = verb[:-1]
  front_change = verb[:-2] #for sa ka

  #五段動詞
  if last_char != "る":
    masu_type=front_chars+str(i[u.index(last_char)]) +"ます"
    if last_char =="う":
      nai_type=front_chars+str(a[u.index(last_char)+9]) +"ない"#結尾う的ない變法比較不一樣
    else:
      nai_type=front_chars+str(a[u.index(last_char)]) +"ない"

    #因為辭書形字尾一定是u段 且前面也排除非u段的了 所以可以簡化


    #て形た形音變判斷
    if verb == "いく" or verb =="行く":
      ta_type= front_chars + "った"
      te_type= front_chars + "って"
      #い音便中的特例

    if last_char in ["う", "つ"]:
      ta_type= front_chars + "った"
      te_type= front_chars + "って"
      #促音便 

    if (verb!="いく" and verb !="行く") and last_char in ["く", "ぐ"]:
      ta_type= front_chars + 'い' + ("た" if last_char == "く" else "だ")
      te_type=front_chars + 'い' + ("て" if last_char == "く" else "で")
      #い音便 排除特例

    if last_char == "す":
      ta_type= front_chars +"した"
      te_type=front_chars +"して"

    if last_char in ["ぶ", "ぬ", "む"]:
      ta_type= front_chars +"んだ"
      te_type= front_chars +"んで"
      #鼻音便

    list_1.append([verb,masu_type,te_type,ta_type,nai_type])

  elif last_char=="る" and (last2_char in a or last2_char in u or last2_char in o)and (verb!="くる" or verb!="来る")and last12_char !="する" or (verb=="かえる"or verb =="帰る"):
    masu_type=front_chars+"ります"
    ta_type= front_chars + "った"
    te_type= front_chars + "って"
    #促音便 

    if verb =="ある":
      nai_type="ない"#ある的ない變法比較不一樣
    else:
      nai_type=front_chars+str(a[u.index(last_char)]) +"ない"

    list_1.append([verb,masu_type,te_type,ta_type,nai_type])

  else:    
    #上一段
    if last_char == "る" and last2_char in i:
      masu_type=front_chars+"ます"
      te_type=front_chars+"て"
      ta_type=front_chars+"た"
      nai_type=front_chars+"ない"
      list_2.append([verb,masu_type,te_type,ta_type,nai_type])

    #下一段
    elif last_char == "る" and last2_char in e: #and (verb !="かえる"or verb !="帰る"):
      masu_type=front_chars+"ます"
      te_type=front_chars+"て"
      ta_type=front_chars+"た"
      nai_type=front_chars+"ない"
      list_3.append([verb,masu_type,te_type,ta_type,nai_type])

  #か行變格
  if verb =="くる" or verb =="来る":
    masu_type=front_change+"きます"
    te_type=front_change+"きて"
    ta_type=front_change+"きた"
    nai_type=front_change+"こない"
    list_4.append([verb,masu_type,te_type,ta_type,nai_type])
  #さ行變格
  if last12_char =="する":
    masu_type=front_change+"します"
    te_type=front_change+"して"
    ta_type=front_change+"した"
    nai_type=front_change+"しない"
    list_5.append([verb,masu_type,te_type,ta_type,nai_type])



  list_voca.append([verb,masu_type,te_type,ta_type,nai_type])

  file=open("voca1.txt","a",encoding="utf-8")
  file.write(verb+"\t")  
  file.write(masu_type+"\t")
  file.write(te_type+"\t")
  file.write(ta_type+"\t")
  file.write(nai_type+"\n")

  file2=open("voca2.txt","a",encoding="utf-8")
  file2.write(verb+"\n")  
  file2.write("ます形:"+masu_type+"\n")
  file2.write("て形:"+te_type+"\n")
  file2.write("た形:"+ta_type+"\n")
  file2.write("ない形:"+nai_type+"\n")
  file2.write("\n")


  print(verb)
  print("ます形:",masu_type)
  print("て形:",te_type)
  print("た形:",ta_type)
  print("ない形:",nai_type)
  print()






clear_output()
print("輸入日文辭書形，查詢動詞變化。")
print("欲結束查詢，可輸入leave\n")
print("查詢結束\n\n")



print("---------------------------------------\n")

print("查詢紀錄\n")

print("---五段動詞---")
if len(list_1)==0:
  print("無")
else:
  for list in list_1:
    print(list[0])
    print("ます形:",list[1])
    print("て形:",list[2])
    print("た形:",list[3])
    print("ない形:",list[4])
    print()

print("---上一段動詞---")
if len(list_2)==0:
  print("無")
else:
  for list in list_2:
    print(list[0])
    print("ます形:",list[1])
    print("て形:",list[2])
    print("た形:",list[3])
    print("ない形:",list[4])
    print()

print("---下一段動詞---")
if len(list_3)==0:
  print("無")
else:
  for list in list_3:
    print(list[0])
    print("ます形:",list[1])
    print("て形:",list[2])
    print("た形:",list[3])
    print("ない形:",list[4])
    print()

print("---か行變格動詞---")
if len(list_4)==0:
  print("無")
else:
  for list in list_4:
    print(list[0])
    print("ます形:",list[1])
    print("て形:",list[2])
    print("た形:",list[3])
    print("ない形:",list[4])
    print()

print("---さ行變格動詞---")
if len(list_5)==0:
  print("無")
else:
  for list in list_5:
    print(list[0])
    print("ます形:",list[1])
    print("て形:",list[2])
    print("た形:",list[3])
    print("ない形:",list[4])
    print()



#print(dic_list)

file.close()
file2.close()